
services:
  db_postgres:
    image: postgres:16
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: dars2
    ports:
      - "5430:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
  app:
    build: .
    container_name: nest_dars4
    restart: always
    ports:
      - "3131:3000"
    env_file:
      - .env
    depends_on:
      - db_postgres
    command: >
      sh -c "
        npx prisma generate &&
        npx prisma migrate deploy &&
        npm run start:prod
      "
volumes:
  pg_data:

